name: Run Gradle Assemble
on:
  push:
    branches:
      - master
      - main
jobs:
  jar:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build
      
    - uses: actions/upload-artifact@v2
      with:
        name: jar
        path: build/libs

  release:
    name: Release
    needs: jar
    if: startsWith(github.event.commits[0].message, 'Update')
    runs-on: ubuntu-latest
    steps:
      - name: Download Jar from build
        uses: actions/download-artifact@v2
        with:
          name: jar 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
      - name: Upload Release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: OCR-NN-1.0.jar
          asset_name: HandWrittenDigitRecognition-${{ github.run_number }}.jar # ${{ github.event.commits[0].message }}
          asset_content_type: application/zip